### ISSUE TITLE
Historiable is not a word

### ISSUE THREAD

**Issue by OzanKurt** [iFeras93/historiable-model#2]

**Comment by iFeras93** [comment]
What is your suggested name?

**Comment by EmmaPurple** [comment]
The actual naming is ok to me.
But as alternatives I would look around the word historicize / historicise
https://www.merriam-webster.com/dictionary/historicize

EDIT: But as I said: I don't mind the naming (as a foreign language speaker!). I read the word and immediately knew what was meant.

**Comment by iFeras93** [comment]
@EmmaPurple thanks for your comments.

@OzanKurt there's any suggested name from you ?

**Comment by iFeras93** [comment]
@OzanKurt I will think of a new name for this package.
thank you :).
